spring:
  application:
    name: zonas
  datasource:
    url: jdbc:postgresql://localhost:5434/zonasDB
    username: kfamaguana
    password: espe123
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      # 'update' actualiza el esquema automáticamente, 'create-drop' lo borra al apagar, 'validate' solo verifica, 'none' no hace nada.
      ddl-auto: update 
    show-sql: true # Muestra las consultas SQL en la consola (útil para desarrollo)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true # Formatea el SQL en la consola para que sea legibl
